artifacts_root: artifacts

data_transformation:
  root_dir: artifacts/data_transformation

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/processed_dataset

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/processed_dataset
  model_path: artifacts/model_trainer/checkpoint-1

  metric_file_name: artifacts/model_evaluation/metrics.csv
